# Acme/UserBundle/Resources/config/admin.yml
services:
    sonata.admin.user:
        class: Acme\UserBundle\Admin\UsersAdmin
        tags:
           
        arguments:
            - ~
            - Acme\UserBundle\Entity\Users
            - AcmeUserBundle:UsersAdmin
        calls:
            - [ setTranslationDomain, [AcmeUserBundle]]
            